# Generated by Django 6.0.6 on 2026-07-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_teacher_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='img',
            field=models.ImageField(default='img/default.png', upload_to='img/'),
        ),
    ]
