# Generated by Django 6.0.6 on 2026-06-30 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('name', models.CharField(max_length=100)),
                ('creator_name', models.CharField(max_length=50)),
                ('participant_count', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
            ],
        ),
    ]
